monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                level: debug
                handler: streamed
                channels: ["!event"]
            streamed:
                type: rotating_file
                max_files: 3
                path: "%kernel.logs_dir%/%kernel.environment%.log"
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: critical
                handler: streamed
                # handler:      grouped
            # grouped:
            #     type:    group
            #     members: [streamed, deduplication]
            streamed:
                type: rotating_file
                max_files: 30
                path: "%kernel.logs_dir%/%kernel.environment%.log"

            # deduplication:
            #     type:    deduplication
            #     handler: symfony_mailer
            # symfony_mailer:
            #     # symfony_mailer needs symfony/monolog-bundle >= 3.6
            #     type:       symfony_mailer
            #     from_email: '%error_mail_from%'
            #     to_email:   '%error_mail_to%'
            #     subject:    'An Error Occurred!'
            #     level:      debug
            #     formatter:  monolog.formatter.html
            #     content_type: text/html

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
